# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python checks

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: astral-sh/setup-uv@v6.1.0
    - name: Install dependencies
      run: uv sync
    - name: Lint with ruff
      run: uvx ruff check .
    - name: Format with ruff
      run: uvx ruff format --check .
    - name: Build
      run: uv build
