name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read
jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: astral-sh/setup-uv@v6.1.0
    - name: Install dependencies
      run: uv sync
    - name: Lint with ruff
      run: uvx ruff check .
    - name: Format with ruff
      run: uvx ruff format --check .
    - name: Build
      run: uv build
    - name: Upload distributions
      uses: actions/upload-artifact@v4
      with:
        name: release-dists
        path: dist/
  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/raiplaysound/
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
